-- Additional prescription-required medicines
INSERT INTO medicines (id, category_id, brand_name, generic_name, manufacturer, strength, dosage_form, price, discount_percent, stock_quantity, image_url, description, uses, dosage_instructions, side_effects, warnings, storage_conditions, requires_prescription, is_featured, rating) VALUES
 ('med_azithro', 'cat_antibiotics', 'Azithromycin', 'Azithromycin', 'Pfizer', '250mg', 'Tablet', 480, 0, 180, '', 'Macrolide antibiotic for respiratory and skin infections.', 'Respiratory infections, skin infections', 'As prescribed by physician', 'Diarrhea, nausea, abdominal pain', 'Complete full course; prescription required', 'Store below 25°C', 1, 0, 4.3),
 ('med_cipro', 'cat_antibiotics', 'Ciprofloxacin', 'Ciprofloxacin', 'Bayer', '500mg', 'Tablet', 520, 0, 160, '', 'Fluoroquinolone antibiotic for serious bacterial infections.', 'Urinary tract infections, bone infections', 'As prescribed by physician', 'Nausea, dizziness, tendon pain', 'Avoid dairy products; prescription required', 'Store below 25°C', 1, 0, 4.2),
 ('med_losartan', 'cat_bp', 'Cozaar', 'Losartan', 'Merck', '50mg', 'Tablet', 450, 0, 200, '', 'Angiotensin II receptor blocker for blood pressure.', 'Hypertension, diabetic nephropathy', 'Once daily as prescribed', 'Dizziness, back pain, upper respiratory infection', 'Prescription required; do not use in pregnancy', 'Store below 25°C', 1, 0, 4.4),
 ('med_atenolol', 'cat_bp', 'Tenormin', 'Atenolol', 'AstraZeneca', '50mg', 'Tablet', 360, 0, 190, '', 'Beta-blocker for hypertension and chest pain.', 'Hypertension, angina pectoris', 'Once daily as prescribed', 'Fatigue, slow heart rate, cold extremities', 'Do not stop suddenly; prescription required', 'Store below 25°C', 1, 0, 4.3),
 ('med_insulin', 'cat_diabetes', 'Humulin R', 'Insulin (Regular)', 'Eli Lilly', '100IU/ml', 'Injection', 1800, 0, 100, '', 'Short-acting insulin for blood sugar control.', 'Type 1 and Type 2 diabetes', 'As prescribed by physician', 'Hypoglycemia, injection site reactions', 'Prescription required; requires refrigeration', 'Refrigerate 2-8°C before opening', 1, 1, 4.5),
 ('med_glibenclamide', 'cat_diabetes', 'Daonil', 'Glibenclamide', 'Sanofi', '5mg', 'Tablet', 280, 0, 250, '', 'Sulfonylurea for type 2 diabetes blood sugar control.', 'Type 2 diabetes', 'As prescribed, usually before breakfast', 'Hypoglycemia, weight gain', 'Prescription required; take with meals', 'Store below 25°C', 1, 0, 4.1),
 ('med_prednisolone', 'cat_pain', 'Prednisolone', 'Prednisolone', 'Various', '5mg', 'Tablet', 320, 0, 200, '', 'Corticosteroid for inflammation and immune conditions.', 'Autoimmune diseases, severe allergies, asthma', 'As prescribed; taper gradually', 'Weight gain, mood changes, insomnia', 'Do not stop abruptly; prescription required', 'Store below 25°C', 1, 0, 4.0),
 ('med_omeprazole_rx', 'cat_pain', 'Losec', 'Omeprazole', 'AstraZeneca', '20mg', 'Capsule', 600, 0, 180, '', 'Proton pump inhibitor for severe acid reflux.', 'GERD, gastric ulcers, H. pylori eradication', 'Once daily before breakfast as prescribed', 'Headache, abdominal pain', 'Prescription required for long-term use', 'Store below 25°C', 1, 0, 4.4),
 ('med_fluconazole', 'cat_skin', 'Diflucan', 'Fluconazole', 'Pfizer', '150mg', 'Capsule', 550, 0, 150, '', 'Antifungal for systemic and severe fungal infections.', 'Fungal infections of the throat, lungs, blood', 'As prescribed by physician', 'Nausea, headache, abdominal pain', 'Prescription required; check liver function', 'Store below 25°C', 1, 0, 4.3),
 ('med_salbutamol', 'cat_allergy', 'Ventolin', 'Salbutamol', 'GSK', '100mcg', 'Inhaler', 680, 0, 200, '', 'Bronchodilator for asthma and breathing difficulties.', 'Asthma, COPD, bronchospasm', 'As needed or as prescribed', 'Tremor, palpitations, headache', 'Prescription required; rinse mouth after use', 'Store below 30°C; protect from light', 1, 1, 4.6),
 ('med_levothyroxine', 'cat_diabetes', 'Euthyrox', 'Levothyroxine', 'Merck', '50mcg', 'Tablet', 400, 0, 200, '', 'Thyroid hormone replacement for hypothyroidism.', 'Hypothyroidism, thyroid hormone deficiency', 'Once daily on empty stomach as prescribed', 'Weight changes, palpitations, tremor', 'Prescription required; take 30-60 min before food', 'Store below 25°C', 1, 0, 4.5);
