-- Migration 0005: Kenyan Medicine Master Database + Inventory Management
-- This is the comprehensive preloaded database of medicines available in Kenya.
-- Admins/pharmacists only manage stock quantities, not create medicines from scratch.

-- =========================================================================
-- INVENTORY MANAGEMENT TABLES
-- =========================================================================

CREATE TABLE IF NOT EXISTS suppliers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  contact_person TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS stock_batches (
  id TEXT PRIMARY KEY,
  medicine_id TEXT NOT NULL REFERENCES medicines(id),
  supplier_id TEXT REFERENCES suppliers(id),
  batch_number TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  purchase_price REAL NOT NULL,
  selling_price REAL,
  expiry_date TEXT NOT NULL,
  received_date TEXT NOT NULL DEFAULT (datetime('now')),
  notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_batches_medicine ON stock_batches(medicine_id);
CREATE INDEX IF NOT EXISTS idx_batches_expiry ON stock_batches(expiry_date);

-- =========================================================================
-- NEW CATEGORIES (Kenyan market)
-- =========================================================================

INSERT INTO categories (id, name, slug, icon, requires_prescription) VALUES
 ('cat_pain_killers', 'Pain Killers', 'pain-killers', '💊', 0),
 ('cat_antimalarials', 'Antimalarials', 'antimalarials', '🦟', 1),
 ('cat_heart', 'Heart Medicines', 'heart-medicines', '❤️', 1),
 ('cat_asthma', 'Asthma & Respiratory', 'asthma-respiratory', '🫁', 1),
 ('cat_cough', 'Cough & Cold', 'cough-cold', '🤧', 0),
 ('cat_ulcer', 'Ulcer & Gastric', 'ulcer-gastric', '🩺', 0),
 ('cat_antifungal', 'Antifungal', 'antifungal', '🔬', 1),
 ('cat_eye', 'Eye Care', 'eye-care', '👁️', 1),
 ('cat_ear', 'Ear Care', 'ear-care', '👂', 0),
 ('cat_skin_2', 'Skin Care Medicines', 'skin-care-medicines', '🧴', 1),
 ('cat_family_plan', 'Family Planning', 'family-planning', '🚼', 1),
 ('cat_pregnancy', 'Pregnancy & Maternal', 'pregnancy-maternal', '🤰', 0),
 ('cat_children', 'Childrens Medicine', 'childrens-medicine', '👶', 1),
 ('cat_hiv', 'HIV / ARVs', 'hiv-arvs', '🧬', 1),
 ('cat_tb', 'TB Medicines', 'tb-medicines', '🫁', 1),
 ('cat_deworming', 'Deworming', 'deworming', '🪱', 0),
 ('cat_anti_seizure', 'Anti-Seizure', 'anti-seizure', '🧠', 1),
 ('cat_mental_health', 'Mental Health', 'mental-health', '🧘', 1),
 ('cat_controlled', 'Controlled Medicines', 'controlled-medicines', '🔒', 1);

-- =========================================================================
-- COMPREHENSIVE KENYAN MEDICINE DATABASE
-- =========================================================================

-- ── Pain Killers ──────────────────────────────────────────────────────────
INSERT INTO medicines (id, category_id, brand_name, generic_name, manufacturer, strength, dosage_form, price, discount_percent, stock_quantity, image_url, description, uses, dosage_instructions, side_effects, warnings, storage_conditions, requires_prescription, is_featured, rating) VALUES
 ('km_panadol', 'cat_pain_killers', 'Panadol', 'Paracetamol', 'GSK Kenya', '500mg', 'Tablet', 150, 0, 500, '', 'Fast-acting pain and fever relief. Kenya''s most trusted pain reliever.', 'Headache, fever, muscle aches, dental pain, period pain', '1-2 tablets every 4-6 hours. Max 8 tablets in 24 hours.', 'Rare: nausea, skin rash. Overdose causes liver damage.', 'Do not exceed recommended dose. Avoid with liver disease.', 'Store below 25°C', 0, 1, 4.8),
 ('km_paracetamol_susp', 'cat_pain_killers', 'Panadol Baby', 'Paracetamol', 'GSK Kenya', '120mg/5ml', 'Suspension', 200, 0, 400, '', 'Paracetamol suspension for children fever and pain.', 'Fever, mild to moderate pain in children', 'As per age/weight on包装', 'Rare: nausea, allergic reactions', 'Do not exceed recommended dose for child''s age', 'Store below 25°C', 0, 1, 4.7),
 ('km_ibuprofen', 'cat_pain_killers', 'Brufen', 'Ibuprofen', 'Abbott', '400mg', 'Tablet', 180, 0, 600, '', 'Anti-inflammatory pain reliever for stronger pain.', 'Pain, inflammation, fever, arthritis, period pain', '1 tablet 2-3 times daily with food', 'Stomach upset, nausea, dizziness', 'Take with food. Avoid if peptic ulcer. Caution in asthma.', 'Store below 25°C', 0, 1, 4.6),
 ('km_ibuprofen_susp', 'cat_pain_killers', 'Brufen Syrup', 'Ibuprofen', 'Abbott', '100mg/5ml', 'Suspension', 280, 0, 350, '', 'Ibuprofen syrup for children pain and fever.', 'Fever, pain, inflammation in children', 'As per age/weight on包装', 'Stomach upset, nausea', 'Take with food. Not for children under 3 months.', 'Store below 25°C', 0, 0, 4.5),
 ('km_diclofenac', 'cat_pain_killers', 'Voltaren', 'Diclofenac', 'Novartis', '50mg', 'Tablet', 220, 0, 400, '', 'Strong anti-inflammatory for joint and muscle pain.', 'Arthritis, back pain, joint pain, muscle sprains', '1 tablet 2-3 times daily with food', 'Stomach pain, nausea, dizziness, fluid retention', 'Take with food. Avoid in peptic ulcer and kidney disease.', 'Store below 25°C', 1, 0, 4.4),
 ('km_diclofenac_gel', 'cat_pain_killers', 'Voltaren Emulgel', 'Diclofenac', 'Novartis', '1%', 'Gel', 350, 0, 300, '', 'Topical anti-inflammatory gel for localized pain.', 'Joint pain, muscle sprains, sports injuries', 'Apply thin layer 3-4 times daily', 'Skin irritation at application site', 'Do not use on broken skin. Avoid sun exposure.', 'Store below 25°C', 0, 0, 4.5),
 ('km_aspirin', 'cat_pain_killers', 'Disprin', 'Aspirin', 'Reckitt', '300mg', 'Tablet', 120, 0, 500, '', 'Pain reliever and blood thinner.', 'Headache, fever, pain, prevention of blood clots', '1-2 tablets as needed. Dissolve in water.', 'Stomach upset, bleeding risk', 'Not for children under 16 (Reye''s syndrome). Avoid in bleeding disorders.', 'Store below 25°C', 0, 0, 4.3),
 ('km_naproxen', 'cat_pain_killers', 'Naprosyn', 'Naproxen', 'Roche', '250mg', 'Tablet', 300, 0, 200, '', 'Long-acting anti-inflammatory for persistent pain.', 'Arthritis, back pain, period pain, gout', '1 tablet twice daily with food', 'Stomach upset, dizziness, headache', 'Take with food. Avoid in kidney disease and peptic ulcer.', 'Store below 25°C', 1, 0, 4.3),
 ('km_tramadol', 'cat_pain_killers', 'Tramal', 'Tramadol', 'Grünenthal', '50mg', 'Capsule', 400, 0, 150, '', 'Strong pain reliever for moderate to severe pain.', 'Severe pain, post-surgical pain, cancer pain', '1 capsule every 6 hours as prescribed', 'Nausea, constipation, dizziness, drowsiness', 'Controlled substance. Risk of dependence. Prescription required.', 'Store below 25°C', 1, 0, 4.2),
 ('km_celecoxib', 'cat_pain_killers', 'Celebrex', 'Celecoxib', 'Pfizer', '200mg', 'Capsule', 800, 0, 100, '', 'COX-2 inhibitor with lower stomach risk.', 'Osteoarthritis, rheumatoid arthritis, acute pain', '1 capsule once or twice daily with food', 'Stomach upset, headache, fluid retention', 'Caution in heart disease. Prescription required.', 'Store below 25°C', 1, 0, 4.4),
 ('km_meloxicam', 'cat_pain_killers', 'Mobic', 'Meloxicam', 'Boehringer', '15mg', 'Tablet', 350, 0, 180, '', 'Once-daily anti-inflammatory for arthritis.', 'Osteoarthritis, rheumatoid arthritis', '1 tablet once daily with food', 'Stomach upset, dizziness, headache', 'Take with food. Avoid in kidney disease.', 'Store below 25°C', 1, 0, 4.3),
 ('km_ketorolac', 'cat_pain_killers', 'Toradol', 'Ketorolac', 'Roche', '10mg', 'Tablet', 450, 0, 120, '', 'Potent short-term pain relief.', 'Severe acute pain (short-term use only)', '1 tablet every 4-6 hours. Max 5 days.', 'Stomach upset, dizziness, headache', 'Max 5 days use. Avoid in kidney disease and peptic ulcer.', 'Store below 25°C', 1, 0, 4.2),
 ('km_piroxicam', 'cat_pain_killers', 'Feldene', 'Piroxicam', 'Pfizer', '20mg', 'Capsule', 280, 0, 200, '', 'Long-acting anti-inflammatory.', 'Arthritis, joint pain', '1 capsule daily with food', 'Stomach upset, dizziness, rash', 'Take with food. Not for elderly without monitoring.', 'Store below 25°C', 1, 0, 4.1),
 ('km_paracetamol_1g', 'cat_pain_killers', 'Paracetamol', 'Paracetamol', 'Various', '1g', 'Tablet', 80, 0, 800, '', 'Generic paracetamol 1g for adult pain and fever.', 'Headache, fever, body aches', '1 tablet every 6 hours. Max 4g/day.', 'Rare: nausea, liver damage at overdose', 'Do not exceed 4g in 24 hours. Avoid with liver disease.', 'Store below 25°C', 0, 0, 4.5),

-- ── Antibiotics ──────────────────────────────────────────────────────────
 ('km_amoxicillin', 'cat_antibiotics', 'Amoxil', 'Amoxicillin', 'GSK Kenya', '500mg', 'Capsule', 350, 5, 300, '', 'Broad-spectrum antibiotic for common bacterial infections.', 'Upper respiratory infections, urinary tract infections, skin infections', '500mg every 8 hours for 5-7 days as prescribed', 'Diarrhea, nausea, skin rash, allergic reactions', 'Complete full course. Prescription required. Not for viral infections.', 'Store below 25°C', 1, 0, 4.4),
 ('km_augmentin', 'cat_antibiotics', 'Augmentin', 'Amoxicillin/Clavulanate', 'GSK Kenya', '625mg', 'Tablet', 650, 0, 200, '', 'Amoxicillin with clavulanate for resistant infections.', 'Respiratory infections, sinusitis, UTI, skin infections', '1 tablet every 8 hours with food', 'Diarrhea, nausea, vomiting, rash', 'Take with food to reduce GI upset. Prescription required.', 'Store below 25°C', 1, 0, 4.5),
 ('km_azithromycin_250', 'cat_antibiotics', 'Zithromax', 'Azithromycin', 'Pfizer', '250mg', 'Tablet', 480, 0, 250, '', 'Macrolide antibiotic, 3-day course for many infections.', 'Respiratory infections, STIs, skin infections', '500mg day 1, then 250mg days 2-5', 'Diarrhea, nausea, headache, abdominal pain', 'Complete full course. Prescription required.', 'Store below 25°C', 1, 0, 4.4),
 ('km_ciprofloxacin', 'cat_antibiotics', 'Ciproxin', 'Ciprofloxacin', 'Bayer', '500mg', 'Tablet', 520, 0, 250, '', 'Fluoroquinolone antibiotic for serious infections.', 'UTI, respiratory infections, bone infections, typhoid', '500mg every 12 hours for 7-14 days', 'Nausea, dizziness, tendon pain, photosensitivity', 'Avoid dairy products. Avoid sun exposure. Prescription required.', 'Store below 25°C', 1, 0, 4.3),
 ('km_metronidazole', 'cat_antibiotics', 'Flagyl', 'Metronidazole', 'Sanofi', '400mg', 'Tablet', 180, 0, 400, '', 'Antibiotic for anaerobic bacteria and parasites.', 'Amoebic dysentery, giardia, dental infections, bacterial vaginosis', '400mg every 8 hours for 5-7 days', 'Metallic taste, nausea, dark urine', 'Avoid alcohol during and 48h after treatment. Prescription required.', 'Store below 25°C', 1, 0, 4.3),
 ('km_ceftriaxone', 'cat_antibiotics', 'Rocephin', 'Ceftriaxone', 'Roche', '1g', 'Injection', 800, 0, 80, '', 'Third-generation cephalosporin for severe infections.', 'Severe pneumonia, meningitis, typhoid, hospital infections', 'As prescribed by physician (IM/IV)', 'Injection site pain, diarrhea, rash', 'Prescription required. Administer by healthcare professional.', 'Store below 25°C', 1, 0, 4.5),
 ('km_cefuroxime', 'cat_antibiotics', 'Zinnat', 'Cefuroxime', 'GSK Kenya', '250mg', 'Tablet', 550, 0, 200, '', 'Second-generation cephalosporin antibiotic.', 'Respiratory infections, UTI, skin infections, Lyme disease', '250mg twice daily for 5-10 days', 'Diarrhea, nausea, headache', 'Prescription required. Complete full course.', 'Store below 25°C', 1, 0, 4.3),
 ('km_doxycycline', 'cat_antibiotics', 'Vibramycin', 'Doxycycline', 'Pfizer', '100mg', 'Capsule', 300, 0, 300, '', 'Tetracycline antibiotic for malaria prevention and infections.', 'Malaria prevention, respiratory infections, acne, STIs', '100mg once or twice daily as prescribed', 'Photosensitivity, nausea, esophageal irritation', 'Take with plenty of water. Avoid sun. Not for pregnant women.', 'Store below 25°C', 1, 0, 4.4),
 ('km_erythromycin', 'cat_antibiotics', 'Erythrocin', 'Erythromycin', 'Various', '500mg', 'Tablet', 250, 0, 250, '', 'Macrolide antibiotic for penicillin-allergic patients.', 'Respiratory infections, skin infections, syphilis', '500mg every 6-8 hours', 'Nausea, stomach cramps, diarrhea', 'Take on empty stomach or with food. Prescription required.', 'Store below 25°C', 1, 0, 4.2),
 ('km_flucloxacillin', 'cat_antibiotics', 'Floxapen', 'Flucloxacillin', 'Various', '500mg', 'Capsule', 380, 0, 200, '', 'Penicillin for skin and soft tissue infections.', 'Cellulitis, infected wounds, skin abscesses', '500mg every 6 hours', 'Nausea, diarrhea, rash', 'Prescription required. Not for penicillin allergy.', 'Store below 25°C', 1, 0, 4.2),
 ('km_nitrofurantoin', 'cat_antibiotics', 'Macrobid', 'Nitrofurantoin', 'Various', '100mg', 'Capsule', 320, 0, 250, '', 'Antibiotic specifically for urinary tract infections.', 'Uncomplicated UTI', '100mg twice daily for 5-7 days', 'Nausea, headache, dark urine', 'Take with food. Avoid in kidney impairment.', 'Store below 25°C', 1, 0, 4.4),
 ('km_cotrimoxazole', 'cat_antibiotics', 'Bactrim', 'Cotrimoxazole', 'Roche', '480mg', 'Tablet', 150, 0, 350, '', 'Sulfonamide antibiotic for various infections.', 'UTI, respiratory infections, traveler''s diarrhea, PCP prophylaxis', '1-2 tablets twice daily as prescribed', 'Nausea, rash, allergic reactions', 'Prescription required. Check for sulfa allergy.', 'Store below 25°C', 1, 0, 4.2),
 ('km_clarithromycin', 'cat_antibiotics', 'Klacid', 'Clarithromycin', 'Abbott', '500mg', 'Tablet', 700, 0, 150, '', 'Macrolide antibiotic for respiratory and skin infections.', 'H. pylori, pneumonia, skin infections', '500mg twice daily for 7-14 days', 'Nausea, diarrhea, headache, taste disturbance', 'Prescription required. Many drug interactions.', 'Store below 25°C', 1, 0, 4.3),
 ('km_clindamycin', 'cat_antibiotics', 'Dalacin', 'Clindamycin', 'Pfizer', '300mg', 'Capsule', 450, 0, 150, '', 'Antibiotic for serious anaerobic and skin infections.', 'Severe skin infections, dental infections, bacterial vaginosis', '300mg every 6-8 hours', 'Diarrhea, nausea, rash', 'Prescription required. Can cause severe diarrhea.', 'Store below 25°C', 1, 0, 4.2),
 ('km_levofloxacin', 'cat_antibiotics', 'Tavanic', 'Levofloxacin', 'Sanofi', '500mg', 'Tablet', 650, 0, 120, '', 'Advanced fluoroquinolone for severe infections.', 'Severe pneumonia, complicated UTI, sinusitis', '500mg once daily for 7-14 days', 'Nausea, diarrhea, headache, tendon pain', 'Avoid sun. Prescription required. Last resort antibiotic.', 'Store below 25°C', 1, 0, 4.3),

-- ── Antimalarials ────────────────────────────────────────────────────────
 ('km_coartem', 'cat_antimalarials', 'Coartem', 'Artemether/Lumefantrine', 'Novartis', '20/120mg', 'Tablet', 500, 0, 400, '', 'First-line treatment for uncomplicated malaria in Kenya.', 'Uncomplicated Plasmodium falciparum malaria', 'As per weight-based dosing over 3 days with fatty food', 'Headache, dizziness, nausea, loss of appetite', 'Take with fatty food. Prescription required. Complete full course.', 'Store below 30°C', 1, 1, 4.6),
 ('km_artefan', 'cat_antimalarials', 'Artefan', 'Artemether/Lumefantrine', 'Bliss GVS', '20/120mg', 'Tablet', 350, 0, 300, '', 'Generic artemisinin combination therapy for malaria.', 'Uncomplicated malaria', 'As per weight-based dosing over 3 days', 'Nausea, vomiting, dizziness', 'Take with food. Complete full course.', 'Store below 30°C', 1, 0, 4.4),
 ('km_artesunate_tab', 'cat_antimalarials', 'Artesunate', 'Artesunate', 'Various', '100mg', 'Tablet', 600, 0, 100, '', 'Artemisinin derivative for malaria treatment.', 'Severe malaria (oral step-down)', 'As prescribed by physician', 'Nausea, vomiting, dizziness', 'Prescription required. For severe malaria under supervision.', 'Store below 30°C', 1, 0, 4.5),
 ('km_quinine', 'cat_antimalarials', 'Quinine', 'Quinine Sulfate', 'Various', '300mg', 'Tablet', 250, 0, 200, '', 'Traditional antimalarial for resistant malaria.', 'Chloroquine-resistant malaria, nocturnal leg cramps', '600mg twice daily for 7 days as prescribed', 'Cinchonism (ringing ears, headache, nausea, visual disturbance)', 'Prescription required. Monitor for cinchonism.', 'Store below 25°C', 1, 0, 4.1),
 ('km_fansidar', 'cat_antimalarials', 'Fansidar', 'Sulfadoxine/Pyrimethamine', 'Roche', '500/25mg', 'Tablet', 200, 0, 300, '', 'Intermittent preventive treatment for malaria in pregnancy.', 'IPTp in pregnancy, malaria treatment (with artesunate)', 'As per national guidelines', 'Nausea, vomiting, allergic reactions', 'Prescription required. Severe skin reactions possible.', 'Store below 25°C', 1, 0, 4.2),
 ('km_lumartem', 'cat_antimalarials', 'Lumartem', 'Artemether/Lumefantrine', 'Various', '20/120mg', 'Tablet', 380, 0, 250, '', 'Generic ACT for uncomplicated malaria.', 'Uncomplicated malaria', 'As per weight-based dosing', 'Nausea, headache, dizziness', 'Take with food. Complete full course.', 'Store below 30°C', 1, 0, 4.3),

-- ── Diabetes ─────────────────────────────────────────────────────────────
 ('km_metformin_500', 'cat_diabetes', 'Glucophage', 'Metformin', 'Merck', '500mg', 'Tablet', 420, 0, 400, '', 'First-line medicine for type 2 diabetes blood sugar control.', 'Type 2 diabetes', '500mg twice daily with meals, increase as prescribed', 'GI upset, diarrhea, metallic taste, vitamin B12 deficiency', 'Take with meals. Prescription required. Avoid in kidney disease.', 'Store below 25°C', 1, 1, 4.5),
 ('km_metformin_850', 'cat_diabetes', 'Glucophage SR', 'Metformin', 'Merck', '850mg', 'Tablet', 550, 0, 300, '', 'Sustained-release metformin for better tolerability.', 'Type 2 diabetes', '850mg once daily with evening meal', 'GI upset (less than IR formulation)', 'Take with food. Prescription required.', 'Store below 25°C', 1, 0, 4.4),
 ('km_glibenclamide', 'cat_diabetes', 'Daonil', 'Glibenclamide', 'Sanofi', '5mg', 'Tablet', 280, 0, 350, '', 'Sulfonylurea for type 2 diabetes.', 'Type 2 diabetes not controlled on metformin alone', '5mg before breakfast as prescribed', 'Hypoglycemia, weight gain', 'Take with breakfast. Risk of hypoglycemia. Prescription required.', 'Store below 25°C', 1, 0, 4.1),
 ('km_gliclazide', 'cat_diabetes', 'Diamicron', 'Gliclazide', 'Servier', '80mg', 'Tablet', 400, 0, 250, '', 'Sulfonylurea with lower hypoglycemia risk.', 'Type 2 diabetes', '80mg once daily with breakfast', 'Hypoglycemia (lower risk than glibenclamide), GI upset', 'Take with breakfast. Prescription required.', 'Store below 25°C', 1, 0, 4.3),
 ('km_glimepiride', 'cat_diabetes', 'Amaryl', 'Glimepiride', 'Sanofi', '2mg', 'Tablet', 500, 0, 150, '', 'Third-generation sulfonylurea for diabetes.', 'Type 2 diabetes', '1-2mg once daily with breakfast', 'Hypoglycemia, weight gain, dizziness', 'Start low. Prescription required.', 'Store below 25°C', 1, 0, 4.3),
 ('km_insulin_actrapid', 'cat_diabetes', 'Actrapid', 'Insulin (Soluble)', 'Novo Nordisk', '100IU/ml', 'Injection', 1200, 0, 80, '', 'Short-acting insulin for blood sugar control.', 'Type 1 and Type 2 diabetes requiring insulin', 'As prescribed by physician', 'Hypoglycemia, injection site reactions, lipodystrophy', 'Prescription required. Keep refrigerated before opening.', 'Refrigerate 2-8°C', 1, 1, 4.5),
 ('km_insulin_mixtard', 'cat_diabetes', 'Mixtard', 'Insulin (Pre-mixed)', 'Novo Nordisk', '30/70', 'Injection', 1100, 0, 80, '', 'Pre-mixed insulin for twice-daily dosing.', 'Type 1 and Type 2 diabetes', 'As prescribed, usually before breakfast and dinner', 'Hypoglycemia, weight gain, injection site reactions', 'Prescription required. Keep refrigerated.', 'Refrigerate 2-8°C', 1, 0, 4.4),
 ('km_insulin_lantus', 'cat_diabetes', 'Lantus', 'Insulin Glargine', 'Sanofi', '100IU/ml', 'Injection', 2500, 0, 50, '', 'Long-acting basal insulin.', 'Type 1 and Type 2 diabetes requiring basal insulin', 'Once daily at same time as prescribed', 'Hypoglycemia, injection site reactions', 'Prescription required. Do not mix with other insulins.', 'Refrigerate 2-8°C', 1, 0, 4.5),
 ('km_januvia', 'cat_diabetes', 'Januvia', 'Sitagliptin', 'MSD', '100mg', 'Tablet', 2200, 0, 60, '', 'DPP-4 inhibitor for type 2 diabetes.', 'Type 2 diabetes', '100mg once daily', 'Nasopharyngitis, headache, upper respiratory infection', 'Prescription required. Do not use in type 1 diabetes.', 'Store below 25°C', 1, 0, 4.4),
 ('km_jardiance', 'cat_diabetes', 'Jardiance', 'Empagliflozin', 'Boehringer', '10mg', 'Tablet', 2800, 0, 50, '', 'SGLT2 inhibitor for diabetes and heart protection.', 'Type 2 diabetes, heart failure', '10mg once daily', 'UTI, genital infections, dehydration', 'Prescription required. Increase fluid intake.', 'Store below 25°C', 1, 0, 4.5),

-- ── Blood Pressure ───────────────────────────────────────────────────────
 ('km_amlodipine_5', 'cat_bp', 'Norvasc', 'Amlodipine', 'Pfizer', '5mg', 'Tablet', 380, 0, 400, '', 'Calcium channel blocker for hypertension.', 'Hypertension, angina', '5mg once daily, increase to 10mg if needed', 'Ankle swelling, dizziness, flushing, headache', 'Prescription required. Do not stop suddenly.', 'Store below 25°C', 1, 0, 4.3),
 ('km_amlodipine_10', 'cat_bp', 'Amlodipine', 'Amlodipine', 'Various', '10mg', 'Tablet', 280, 0, 300, '', 'Generic amlodipine 10mg for blood pressure.', 'Hypertension', '10mg once daily', 'Ankle swelling, dizziness, flushing', 'Prescription required.', 'Store below 25°C', 1, 0, 4.2),
 ('km_losartan_50', 'cat_bp', 'Cozaar', 'Losartan', 'MSD', '50mg', 'Tablet', 450, 0, 300, '', 'ARB for hypertension and kidney protection.', 'Hypertension, diabetic nephropathy', '50mg once daily', 'Dizziness, upper respiratory infection', 'Prescription required. Do not use in pregnancy.', 'Store below 25°C', 1, 0, 4.4),
 ('km_losartan_hctz', 'cat_bp', 'Hyzaar', 'Losartan/HCTZ', 'MSD', '50/12.5mg', 'Tablet', 650, 0, 150, '', 'Combination ARB + diuretic for blood pressure.', 'Hypertension not controlled on monotherapy', '1 tablet once daily', 'Dizziness, diarrhea, upper respiratory infection', 'Prescription required. Monitor electrolytes.', 'Store below 25°C', 1, 0, 4.3),
 ('km_enalapril', 'cat_bp', 'Renitec', 'Enalapril', 'MSD', '10mg', 'Tablet', 300, 0, 250, '', 'ACE inhibitor for hypertension and heart failure.', 'Hypertension, heart failure', '10mg once daily, increase as prescribed', 'Dry cough, dizziness, headache, hyperkalemia', 'Prescription required. Avoid in pregnancy. Monitor kidney function.', 'Store below 25°C', 1, 0, 4.3),
 ('km_lisinopril', 'cat_bp', 'Zestril', 'Lisinopril', 'AstraZeneca', '10mg', 'Tablet', 350, 0, 200, '', 'ACE inhibitor with once-daily dosing.', 'Hypertension, heart failure', '10mg once daily', 'Dry cough, dizziness, headache', 'Prescription required. Avoid in pregnancy.', 'Store below 25°C', 1, 0, 4.3),
 ('km_nifedipine', 'cat_bp', 'Adalat', 'Nifedipine', 'Bayer', '30mg', 'SR Tablet', 250, 0, 250, '', 'Calcium channel blocker for hypertension.', 'Hypertension, angina', '30mg once daily', 'Headache, flushing, ankle swelling, dizziness', 'Prescription required. Do not use sublingual for hypertensive urgency.', 'Store below 25°C', 1, 0, 4.2),
 ('km_atenolol_50', 'cat_bp', 'Tenormin', 'Atenolol', 'AstraZeneca', '50mg', 'Tablet', 360, 0, 300, '', 'Beta-blocker for hypertension and angina.', 'Hypertension, angina, rate control', '50mg once daily', 'Fatigue, slow heart rate, cold extremities, depression', 'Do not stop suddenly. Prescription required.', 'Store below 25°C', 1, 0, 4.3),
 ('km_bisoprolol', 'cat_bp', 'Concor', 'Bisoprolol', 'Merck', '5mg', 'Tablet', 300, 0, 250, '', 'Cardioselective beta-blocker.', 'Hypertension, heart failure, angina', '5mg once daily', 'Fatigue, slow heart rate, dizziness', 'Do not stop suddenly. Prescription required.', 'Store below 25°C', 1, 0, 4.4),
 ('km_carvedilol', 'cat_bp', 'Coreg', 'Carvedilol', 'GSK', '6.25mg', 'Tablet', 400, 0, 150, '', 'Alpha + beta blocker for heart failure.', 'Heart failure, hypertension', '6.25mg twice daily, increase as prescribed', 'Dizziness, fatigue, diarrhea', 'Take with food. Prescription required.', 'Store below 25°C', 1, 0, 4.3),
 ('km_hctz', 'cat_bp', 'Hydrodiuril', 'Hydrochlorothiazide', 'Various', '25mg', 'Tablet', 120, 0, 400, '', 'Thiazide diuretic for blood pressure.', 'Hypertension, edema', '25mg once daily', 'Electrolyte imbalance, dizziness, increased urination', 'Monitor electrolytes. Prescription required.', 'Store below 25°C', 1, 0, 4.2),
 ('km_furosemide', 'cat_bp', 'Lasix', 'Furosemide', 'Sanofi', '40mg', 'Tablet', 150, 0, 350, '', 'Loop diuretic for edema and heart failure.', 'Edema, heart failure, kidney disease', '40mg once daily as prescribed', 'Electrolyte imbalance, dehydration, dizziness', 'Monitor electrolytes and kidney function. Prescription required.', 'Store below 25°C', 1, 0, 4.3),
 ('km_telmisartan', 'cat_bp', 'Micardis', 'Telmisartan', 'Boehringer', '40mg', 'Tablet', 500, 0, 200, '', 'Long-acting ARB for 24-hour blood pressure control.', 'Hypertension', '40mg once daily', 'Dizziness, upper respiratory infection, back pain', 'Prescription required. Do not use in pregnancy.', 'Store below 25°C', 1, 0, 4.4),
 ('km_valartan', 'cat_bp', 'Diovan', 'Valsartan', 'Novartis', '80mg', 'Tablet', 550, 0, 150, '', 'ARB for hypertension and heart failure.', 'Hypertension, heart failure, post-MI', '80mg once daily', 'Dizziness, hyperkalemia, fatigue', 'Prescription required. Monitor kidney function.', 'Store below 25°C', 1, 0, 4.3),

-- ── Heart Medicines ──────────────────────────────────────────────────────
 ('km_clopidogrel', 'cat_heart', 'Plavix', 'Clopidogrel', 'Sanofi', '75mg', 'Tablet', 800, 0, 200, '', 'Antiplatelet medicine to prevent blood clots.', 'Heart attack prevention, stroke prevention, stent patients', '75mg once daily', 'Bleeding, bruising, stomach upset, rash', 'Prescription required. Do not stop without medical advice.', 'Store below 25°C', 1, 0, 4.5),
 ('km_atorvastatin', 'cat_heart', 'Lipitor', 'Atorvastatin', 'Pfizer', '20mg', 'Tablet', 600, 0, 300, '', 'Statin for lowering cholesterol.', 'High cholesterol, cardiovascular prevention', '20mg once daily at bedtime', 'Muscle pain, headache, nausea, liver enzyme elevation', 'Monitor liver function. Prescription required. Avoid grapefruit.', 'Store below 25°C', 1, 0, 4.5),
 ('km_simvastatin', 'cat_heart', 'Zocor', 'Simvastatin', 'MSD', '20mg', 'Tablet', 350, 0, 250, '', 'Statin for cholesterol management.', 'High cholesterol', '20mg once daily at bedtime', 'Muscle pain, headache, GI upset', 'Prescription required. Avoid grapefruit. Max dose with amlodipine.', 'Store below 25°C', 1, 0, 4.3),
 ('km_rosuvastatin', 'cat_heart', 'Crestor', 'Rosuvastatin', 'AstraZeneca', '10mg', 'Tablet', 700, 0, 200, '', 'Potent statin for aggressive cholesterol lowering.', 'High cholesterol, cardiovascular prevention', '10mg once daily', 'Muscle pain, headache, nausea', 'Prescription required. Monitor liver function.', 'Store below 25°C', 1, 0, 4.5),
 ('km_warfarin', 'cat_heart', 'Marevan', 'Warfarin', 'Various', '5mg', 'Tablet', 180, 0, 200, '', 'Anticoagulant for blood clot prevention.', 'Atrial fibrillation, DVT, PE, mechanical heart valves', 'As prescribed (INR-guided dosing)', 'Bleeding, bruising', 'Requires regular INR monitoring. Many food/drug interactions. Prescription required.', 'Store below 25°C', 1, 0, 4.2),
 ('km_rivaroxaban', 'cat_heart', 'Xarelto', 'Rivaroxaban', 'Bayer', '20mg', 'Tablet', 1800, 0, 80, '', 'DOAC for blood clot prevention.', 'Atrial fibrillation, DVT, PE', '20mg once daily with food', 'Bleeding, nausea, headache', 'Prescription required. Take with food. No regular INR monitoring needed.', 'Store below 25°C', 1, 0, 4.4),
 ('km_apixaban', 'cat_heart', 'Eliquis', 'Apixaban', 'BMS/Pfizer', '5mg', 'Tablet', 2200, 0, 60, '', 'DOAC with lower bleeding risk.', 'Atrial fibrillation, DVT, PE', '5mg twice daily', 'Bleeding, nausea', 'Prescription required. Lower bleeding risk than warfarin.', 'Store below 25°C', 1, 0, 4.5),
 ('km_digoxin', 'cat_heart', 'Lanoxin', 'Digoxin', 'GSK', '0.25mg', 'Tablet', 200, 0, 150, '', 'Cardiac glycoside for heart failure and arrhythmias.', 'Heart failure, atrial fibrillation', '0.125-0.25mg once daily as prescribed', 'Nausea, visual disturbance, arrhythmias', 'Narrow therapeutic index. Requires monitoring. Prescription required.', 'Store below 25°C', 1, 0, 4.2),

-- ── Asthma & Respiratory ────────────────────────────────────────────────
 ('km_ventolin_inh', 'cat_asthma', 'Ventolin', 'Salbutamol', 'GSK Kenya', '100mcg', 'Inhaler', 680, 0, 400, '', 'Reliever inhaler for asthma and breathing emergencies.', 'Asthma, COPD, bronchospasm, exercise-induced asthma', '1-2 puffs as needed (max 8 puffs/day)', 'Tremor, palpitations, headache, nervousness', 'Reliever only. Seek medical help if using >3 times/week. Prescription required.', 'Store below 30°C', 1, 1, 4.7),
 ('km_beclomethasone', 'cat_asthma', 'Beclotide', 'Beclomethasone', 'GSK', '200mcg', 'Inhaler', 550, 0, 250, '', 'Preventer inhaler for asthma maintenance.', 'Asthma maintenance, prevention of attacks', '2 puffs twice daily', 'Oral thrush, hoarse voice, cough', 'Rinse mouth after use. Not a reliever. Prescription required.', 'Store below 30°C', 1, 0, 4.3),
 ('km_budesonide', 'cat_asthma', 'Pulmicort', 'Budesonide', 'AstraZeneca', '200mcg', 'Inhaler', 750, 0, 200, '', 'Inhaled corticosteroid for asthma control.', 'Asthma maintenance', '1-2 puffs twice daily', 'Oral thrush, hoarse voice', 'Rinse mouth after use. Prescription required.', 'Store below 30°C', 1, 0, 4.4),
 ('km_seretide', 'cat_asthma', 'Seretide', 'Fluticasone/Salmeterol', 'GSK', '250/25mcg', 'Inhaler', 1200, 0, 150, '', 'Combination preventer + reliever for moderate-severe asthma.', 'Asthma not controlled on ICS alone', '1 puff twice daily', 'Oral thrush, headache, palpitations', 'Rinse mouth after use. Not for acute attacks. Prescription required.', 'Store below 30°C', 1, 0, 4.5),
 ('km_montelukast', 'cat_asthma', 'Singulair', 'Montelukast', 'MSD', '10mg', 'Tablet', 600, 0, 200, '', 'Leukotriene receptor antagonist for asthma.', 'Asthma, allergic rhinitis', '10mg once daily at bedtime', 'Headache, upper respiratory infection, abdominal pain', 'Prescription required. Take at bedtime.', 'Store below 25°C', 1, 0, 4.4),
 ('km_aminophylline', 'cat_asthma', 'Phyllocontin', 'Aminophylline', 'Various', '225mg', 'SR Tablet', 200, 0, 150, '', 'Bronchodilator for chronic asthma.', 'Chronic asthma, COPD', 'As prescribed (narrow therapeutic index)', 'Nausea, headache, palpitations, tremor', 'Requires monitoring. Prescription required.', 'Store below 25°C', 1, 0, 4.1),

-- ── Allergy ──────────────────────────────────────────────────────────────
 ('km_cetirizine_10', 'cat_allergy', 'Zyrtec', 'Cetirizine', 'UCB', '10mg', 'Tablet', 200, 10, 500, '', 'Non-drowsy antihistamine for allergies.', 'Hay fever, urticaria, itching, allergic rhinitis', '1 tablet once daily', 'Mild drowsiness, dry mouth, headache', 'May cause drowsiness. Avoid alcohol.', 'Store below 25°C', 0, 1, 4.7),
 ('km_loratadine', 'cat_allergy', 'Clarityne', 'Loratadine', 'Bayer', '10mg', 'Tablet', 180, 0, 450, '', 'Non-drowsy 24-hour antihistamine.', 'Hay fever, allergic rhinitis, urticaria', '1 tablet once daily', 'Headache, drowsiness (rare), dry mouth', 'Non-drowsy for most people.', 'Store below 25°C', 0, 0, 4.6),
 ('km_chlorpheniramine', 'cat_allergy', 'Allergex', 'Chlorpheniramine', 'Various', '4mg', 'Tablet', 100, 0, 400, '', 'First-generation antihistamine for allergies.', 'Allergic rhinitis, urticaria, insect bites', '4mg every 6-8 hours', 'Drowsiness, dry mouth, blurred vision', 'Causes drowsiness. Avoid driving. Prescription required if >2 weeks.', 'Store below 25°C', 0, 0, 4.2),
 ('km_fexofenadine', 'cat_allergy', 'Telfast', 'Fexofenadine', 'Sanofi', '120mg', 'Tablet', 350, 0, 200, '', 'Non-drowsy antihistamine for severe allergies.', 'Chronic urticaria, severe hay fever', '120mg once daily', 'Headache, nausea, drowsiness (rare)', 'Non-drowsy. Prescription required.', 'Store below 25°C', 0, 0, 4.5),
 ('km_promethazine', 'cat_allergy', 'Phenergan', 'Promethazine', 'Sanofi', '25mg', 'Tablet', 150, 0, 250, '', 'Antihistamine for allergies and nausea.', 'Allergies, motion sickness, nausea, sedation', '25mg at bedtime or as prescribed', 'Severe drowsiness, dry mouth, blurred vision', 'Causes significant drowsiness. Do not drive. Prescription required.', 'Store below 25°C', 1, 0, 4.2),

-- ── Cough & Cold ─────────────────────────────────────────────────────────
 ('km_benylin', 'cat_cough', 'Benylin', 'Dextromethorphan', 'Pfizer', '100ml', 'Syrup', 300, 0, 350, '', 'Cough suppressant for dry cough.', 'Dry cough, cough relief', '10ml every 4-6 hours', 'Drowsiness, nausea', 'Do not use with expectorants. Contains alcohol.', 'Store below 25°C', 0, 1, 4.5),
 ('km_bro_zedex', 'cat_cough', 'Bro-Zedex', 'Ambroxol/Guaifenesin', 'Various', '100ml', 'Syrup', 250, 0, 300, '', 'Expectorant for productive cough.', 'Productive cough with mucus', '10ml 2-3 times daily', 'Nausea, vomiting, diarrhea', 'Drink plenty of water. Prescription required for children <2 years.', 'Store below 25°C', 0, 0, 4.3),
 ('km_actifed', 'cat_cough', 'Actifed', 'Pseudoephedrine/Triprolidine', 'GSK', '100ml', 'Syrup', 280, 0, 300, '', 'Decongestant + antihistamine for cold and flu.', 'Common cold, nasal congestion, runny nose', '5ml every 4-6 hours', 'Drowsiness, dry mouth, insomnia', 'Contains pseudoephedrine (controlled). May cause insomnia.', 'Store below 25°C', 0, 0, 4.3),
 ('km_mucosolvan', 'cat_cough', 'Mucosolvan', 'Ambroxol', 'Boehringer', '30mg', 'Tablet', 200, 0, 250, '', 'Mucolytic for thinning mucus.', 'Productive cough, bronchitis', '30mg 3 times daily', 'GI upset, nausea', 'Drink plenty of water. Prescription required for children.', 'Store below 25°C', 0, 0, 4.3),
 ('km_bisolvon', 'cat_cough', 'Bisolvon', 'Ambroxol', 'Boehringer', '100ml', 'Syrup', 280, 0, 250, '', 'Ambroxol syrup for children cough.', 'Productive cough in children', 'As per age on包装', 'GI upset, nausea', 'Drink plenty of water.', 'Store below 25°C', 0, 0, 4.4),
 ('km_covonia', 'cat_cough', 'Covonia', 'Pholcodine', 'Various', '100ml', 'Syrup', 220, 0, 200, '', 'Pholcodine cough suppressant.', 'Dry cough', '10ml every 4-6 hours', 'Drowsiness, constipation, nausea', 'Do not use with expectorants.', 'Store below 25°C', 0, 0, 4.2),

-- ── Ulcer & Gastric ──────────────────────────────────────────────────────
 ('km_omeprazole_20', 'cat_ulcer', 'Losec', 'Omeprazole', 'AstraZeneca', '20mg', 'Capsule', 600, 0, 350, '', 'Proton pump inhibitor for acid reflux and ulcers.', 'GERD, gastric ulcer, duodenal ulcer, H. pylori eradication', '20mg once daily before breakfast for 2-4 weeks', 'Headache, abdominal pain, diarrhea', 'Long-term use may affect magnesium/calcium. Prescription for >4 weeks.', 'Store below 25°C', 1, 0, 4.4),
 ('km_omeprazole_40', 'cat_ulcer', 'Losec MUPS', 'Omeprazole', 'AstraZeneca', '40mg', 'Tablet', 800, 0, 150, '', 'Higher dose omeprazole for severe conditions.', 'Severe GERD, Zollinger-Ellison, H. pylori triple therapy', '40mg once daily as prescribed', 'Headache, abdominal pain', 'Prescription required.', 'Store below 25°C', 1, 0, 4.3),
 ('km_pantoprazole', 'cat_ulcer', 'Pantodac', 'Pantoprazole', 'Various', '40mg', 'Tablet', 350, 0, 300, '', 'PPI with fewer drug interactions than omeprazole.', 'GERD, gastric ulcer, erosive esophagitis', '40mg once daily before breakfast', 'Headache, GI upset', 'Prescription required for long-term use.', 'Store below 25°C', 1, 0, 4.3),
 ('km_esomeprazole', 'cat_ulcer', 'Nexium', 'Esomeprazole', 'AstraZeneca', '40mg', 'Capsule', 750, 0, 150, '', 'S-isomer of omeprazole for better acid control.', 'GERD, erosive esophagitis', '40mg once daily', 'Headache, abdominal pain, diarrhea', 'Prescription required.', 'Store below 25°C', 1, 0, 4.4),
 ('km_rabeprazole', 'cat_ulcer', 'Pariet', 'Rabeprazole', 'Janssen', '20mg', 'Tablet', 500, 0, 150, '', 'PPI with fastest onset of action.', 'GERD, gastric ulcer', '20mg once daily before breakfast', 'Headache, nausea', 'Prescription required.', 'Store below 25°C', 1, 0, 4.3),
 ('km_famotidine', 'cat_ulcer', 'Pepcid', 'Famotidine', 'MSD', '20mg', 'Tablet', 250, 0, 250, '', 'H2 blocker for mild acid reflux.', 'Heartburn, mild GERD, gastric ulcer', '20mg twice daily or 40mg at bedtime', 'Headache, dizziness, constipation', 'Available OTC. Less potent than PPIs.', 'Store below 25°C', 0, 0, 4.2),
 ('km_gaviscon', 'cat_ulcer', 'Gaviscon', 'Sodium Alginate', 'Reckitt', '500ml', 'Suspension', 400, 0, 200, '', 'Alginate raft for acid reflux relief.', 'Heartburn, GERD, post-meal reflux', '10-20ml after meals and at bedtime', 'Taste disturbance, constipation (rare)', 'Available OTC. Safe in pregnancy.', 'Store below 25°C', 0, 1, 4.5),

-- ── Antifungal ───────────────────────────────────────────────────────────
 ('km_fluconazole_150', 'cat_antifungal', 'Diflucan', 'Fluconazole', 'Pfizer', '150mg', 'Capsule', 550, 0, 250, '', 'Oral antifungal for systemic and vaginal infections.', 'Vaginal candidiasis, oral thrush, systemic fungal infections', '150mg single dose (vaginal) or as prescribed', 'Nausea, headache, abdominal pain', 'Prescription required. Check liver function.', 'Store below 25°C', 1, 0, 4.3),
 ('km_fluconazole_200', 'cat_antifungal', 'Diflucan', 'Fluconazole', 'Pfizer', '200mg', 'Capsule', 700, 0, 150, '', 'Higher dose fluconazole for systemic infections.', 'Systemic fungal infections', '200mg daily as prescribed', 'Nausea, headache, liver enzyme elevation', 'Prescription required. Monitor liver function.', 'Store below 25°C', 1, 0, 4.2),
 ('km_ketoconazole', 'cat_antifungal', 'Nizoral', 'Ketoconazole', 'Janssen', '200mg', 'Tablet', 300, 0, 200, '', 'Oral antifungal for severe skin fungal infections.', 'Severe dermatophytosis, seborrheic dermatitis', '200mg once daily with food', 'Nausea, hepatotoxicity', 'Prescription required. Monitor liver function.', 'Store below 25°C', 1, 0, 4.1),
 ('km_clotrimazole_tab', 'cat_antifungal', 'Canesten', 'Clotrimazole', 'Bayer', '500mg', 'Vaginal Tablet', 250, 0, 300, '', 'Vaginal antifungal tablet for thrush.', 'Vaginal candidiasis', '500mg single vaginal dose at bedtime', 'Local irritation, burning', 'Insert at bedtime. Avoid during menstruation.', 'Store below 25°C', 0, 0, 4.4),
 ('km_nystatin', 'cat_antifungal', 'Mycostatin', 'Nystatin', 'Various', '100,000IU', 'Suspension', 200, 0, 250, '', 'Antifungal for oral thrush.', 'Oral and esophageal candidiasis', '5ml swish and spit 4 times daily', 'Nausea (if swallowed), bad taste', 'Do not swallow. Prescription required for esophageal candidiasis.', 'Store below 25°C', 1, 0, 4.3),
 ('km_terbinafine', 'cat_antifungal', 'Lamisil', 'Terbinafine', 'Novartis', '250mg', 'Tablet', 800, 0, 150, '', 'Antifungal for nail and skin fungal infections.', 'Fungal nail infection, severe ringworm', '250mg once daily for 2-6 weeks', 'GI upset, headache, taste disturbance, liver enzyme elevation', 'Prescription required. Monitor liver function.', 'Store below 25°C', 1, 0, 4.2),
 ('km_terbinafine_cream', 'cat_antifungal', 'Lamisil AT', 'Terbinafine', 'Novartis', '1%', 'Cream', 350, 0, 300, '', 'Topical antifungal for athlete''s foot and ringworm.', 'Athlete''s foot, ringworm, jock itch', 'Apply 1-2 times daily for 1-2 weeks', 'Local irritation, burning', 'Apply to clean dry skin. Complete full course.', 'Store below 25°C', 0, 0, 4.5),
 ('km_miconazole', 'cat_antifungal', 'Daktarin', 'Miconazole', 'Janssen', '2%', 'Cream', 300, 0, 300, '', 'Topical antifungal for skin and nail infections.', 'Athlete''s foot, ringworm, skin candidiasis', 'Apply 2 times daily', 'Local irritation', 'Apply to clean dry skin.', 'Store below 25°C', 0, 0, 4.4),

-- ── Eye Care ─────────────────────────────────────────────────────────────
 ('km_chloramphenicol_eye', 'cat_eye', 'Chloramphenicol', 'Chloramphenicol', 'Various', '0.5%', 'Eye Drops', 150, 0, 300, '', 'Antibiotic eye drops for bacterial conjunctivitis.', 'Bacterial conjunctivitis, eye infections', '1-2 drops every 2-4 hours', 'Temporary stinging, blurred vision', 'Prescription required. Prolonged use may cause blood disorders.', 'Store below 25°C', 1, 0, 4.3),
 ('km_timolol', 'cat_eye', 'Timoptol', 'Timolol', 'MSD', '0.5%', 'Eye Drops', 400, 0, 150, '', 'Beta-blocker eye drops for glaucoma.', 'Glaucoma, ocular hypertension', '1 drop twice daily', 'Eye irritation, headache, fatigue', 'Prescription required. Systemic absorption possible.', 'Store below 25°C', 1, 0, 4.3),
 ('km_artificial_tears', 'cat_eye', 'Visine', 'Carboxymethylcellulose', 'Various', '0.5%', 'Eye Drops', 200, 0, 350, '', 'Lubricating eye drops for dry eyes.', 'Dry eyes, mild eye irritation', '1-2 drops as needed', 'Temporary stinging', 'Available OTC. Do not use with contact lenses.', 'Store below 25°C', 0, 0, 4.4),
 ('km_tobramycin_eye', 'cat_eye', 'Tobrex', 'Tobramycin', 'Alcon', '0.3%', 'Eye Drops', 350, 0, 150, '', 'Aminoglycoside eye drops for severe eye infections.', 'Bacterial eye infections, post-surgical prophylaxis', '1-2 drops every 4-6 hours', 'Eye irritation, allergic reaction', 'Prescription required. Short course only.', 'Store below 25°C', 1, 0, 4.3),
 ('km_cipro_eye', 'cat_eye', 'Ciloxan', 'Ciprofloxacin', 'Alcon', '0.3%', 'Eye Drops', 300, 0, 150, '', 'Fluoroquinolone eye drops for eye infections.', 'Bacterial conjunctivitis, corneal ulcers', '1-2 drops every 2 hours initially', 'Eye irritation, allergic reaction', 'Prescription required.', 'Store below 25°C', 1, 0, 4.3),

-- ── Ear Care ─────────────────────────────────────────────────────────────
 ('km_sofradex', 'cat_ear', 'Sofradex', 'Framycetin/Dexamethasone', 'Sanofi', '10ml', 'Ear/Eye Drops', 200, 0, 250, '', 'Antibiotic + steroid drops for ear and eye infections.', 'Otitis externa, infected eczema of ear canal', '3-4 drops 3-4 times daily', 'Local irritation, burning', 'Do not use for more than 7 days. Prescription required.', 'Store below 25°C', 1, 0, 4.3),
 ('km_ear_drops', 'cat_ear', 'Otomize', 'Neomycin/Polymyxin/Acetic Acid', 'Various', '10ml', 'Ear Drops', 250, 0, 200, '', 'Antibiotic ear drops for ear infections.', 'Otitis externa', '3 drops 3 times daily for 7 days', 'Local irritation', 'Do not use if eardrum is perforated. Prescription required.', 'Store below 25°C', 1, 0, 4.2),
 ('km_cipro_ear', 'cat_ear', 'Ciprofloxacin Ear', 'Ciprofloxacin', 'Various', '0.3%', 'Ear Drops', 200, 0, 150, '', 'Fluoroquinolone ear drops for ear infections.', 'Otitis externa, chronic otitis media', '3-4 drops twice daily for 7-14 days', 'Local irritation, ear pain', 'Prescription required. Warm drops to body temperature before use.', 'Store below 25°C', 1, 0, 4.2),

-- ── Skin Care Medicines ──────────────────────────────────────────────────
 ('km_betnovate', 'cat_skin_2', 'Betnovate', 'Betamethasone', 'GSK', '0.1%', 'Cream', 250, 0, 350, '', 'Potent topical steroid for inflammatory skin conditions.', 'Eczema, psoriasis, dermatitis', 'Apply thin layer 1-2 times daily for max 2 weeks', 'Skin thinning, stretch marks with prolonged use', 'Do not use on face or broken skin for >2 weeks. Prescription required.', 'Store below 25°C', 1, 0, 4.3),
 ('km_hydrocortisone_1', 'cat_skin_2', 'Hydrocortisone', 'Hydrocortisone', 'Various', '1%', 'Cream', 200, 0, 400, '', 'Mild topical steroid for skin irritation.', 'Mild eczema, insect bites, rashes, dermatitis', 'Apply thin layer 1-2 times daily', 'Skin thinning with prolonged use', 'Do not use for >7 days without medical advice.', 'Store below 25°C', 0, 0, 4.2),
 ('km_clotrimazole_cream', 'cat_skin_2', 'Canesten Cream', 'Clotrimazole', 'Bayer', '1%', 'Cream', 200, 0, 350, '', 'Topical antifungal for skin fungal infections.', 'Athlete''s foot, ringworm, skin candidiasis', 'Apply 2 times daily for 2-4 weeks', 'Local irritation, burning', 'Complete full course. Apply to clean dry skin.', 'Store below 25°C', 0, 0, 4.4),
 ('km_gentamicin_cream', 'cat_skin_2', 'Genticin', 'Gentamicin', 'Various', '0.1%', 'Cream', 180, 0, 250, '', 'Antibiotic cream for infected skin lesions.', 'Infected eczema, minor skin wounds', 'Apply 2-3 times daily', 'Local irritation', 'Do not use for >7 days. Prescription required.', 'Store below 25°C', 1, 0, 4.2),
 ('km_silver_sulfadiazine', 'cat_skin_2', 'Flamazine', 'Silver Sulfadiazine', 'Smith Nephew', '1%', 'Cream', 500, 0, 100, '', 'Topical antibiotic for burns.', 'Burns, wound prophylaxis', 'Apply 1-2 times daily under medical supervision', 'Pain at application site, allergic reaction, argyria', 'Prescription required. For moderate to severe burns.', 'Store below 25°C', 1, 0, 4.4),
 ('km_mupirocin', 'cat_skin_2', 'Bactroban', 'Mupirocin', 'GSK', '2%', 'Ointment', 350, 0, 200, '', 'Topical antibiotic for bacterial skin infections.', 'Infected eczema, impetigo, minor wounds', 'Apply 3 times daily for 5-10 days', 'Local burning, stinging', 'Prescription required. Not for large area use.', 'Store below 25°C', 1, 0, 4.3),
 ('km_zinc_ointment', 'cat_skin_2', 'Sudocrem', 'Zinc Oxide', 'Various', '1%', 'Cream', 300, 0, 300, '', 'Barrier cream for nappy rash and minor skin irritation.', 'Nappy rash, minor skin irritation, incontinence rash', 'Apply thick layer as needed', 'None significant', 'Available OTC. Safe for infants.', 'Store below 25°C', 0, 0, 4.6),

-- ── Family Planning ──────────────────────────────────────────────────────
 ('km_postinor2', 'cat_family_plan', 'Postinor-2', 'Levonorgestrel', 'Gedeon Richter', '1.5mg', 'Tablet', 200, 0, 400, '', 'Emergency contraception (morning-after pill).', 'Emergency contraception within 72 hours of unprotected sex', '1 tablet as soon as possible within 72 hours', 'Nausea, vomiting, irregular bleeding, headache', 'Not regular contraception. Prescription required.', 'Store below 25°C', 1, 1, 4.4),
 ('km_microgynon', 'cat_family_plan', 'Microgynon', 'Levonorgestrel/Ethinylestradiol', 'Bayer', '150/30mcg', 'Tablet', 300, 0, 400, '', 'Combined oral contraceptive pill.', 'Contraception, menstrual regulation', '1 tablet daily for 21 days, 7-day break', 'Nausea, breast tenderness, headache, mood changes', 'Not for smokers >35 years. Prescription required.', 'Store below 25°C', 1, 0, 4.3),
 ('km_jadelle', 'cat_family_plan', 'Jadelle', 'Levonorgestrel Implant', 'MSD', '2x75mg', 'Implant', 3000, 0, 50, '', 'Subdermal implant for 5-year contraception.', 'Long-term contraception', 'Inserted subdermally by trained provider', 'Irregular bleeding, headache, weight gain', 'Prescription required. Insertion by trained professional.', 'Store below 25°C', 1, 0, 4.5),
 ('km_depo_provera', 'cat_family_plan', 'Depo-Provera', 'Medroxyprogesterone', 'Pfizer', '150mg/ml', 'Injection', 500, 0, 200, '', 'Injectable contraceptive for 3-month protection.', 'Long-term contraception', '150mg IM every 3 months', 'Irregular bleeding, weight gain, delayed fertility', 'Prescription required. Administered by healthcare professional.', 'Store below 25°C', 1, 0, 4.4),
 ('km_implanon', 'cat_family_plan', 'Implanon NXT', 'Etonogestrel', 'MSD', '68mg', 'Implant', 3500, 0, 40, '', 'Single-rod implant for 3-year contraception.', 'Long-term contraception', 'Inserted subdermally by trained provider', 'Irregular bleeding, headache, acne', 'Prescription required. Insertion by trained professional.', 'Store below 25°C', 1, 0, 4.5),
 ('km_sayana_press', 'cat_family_plan', 'Sayana Press', 'Medroxyprogesterone', 'Pfizer', '104mg/0.65ml', 'Injection', 800, 0, 100, '', 'Self-injectable contraceptive.', 'Long-term contraception (self-administered)', 'Subcutaneous injection every 3 months', 'Irregular bleeding, weight gain', 'Can be self-administered after training. Prescription required.', 'Store below 25°C', 1, 0, 4.3),

-- ── Pregnancy & Maternal ─────────────────────────────────────────────────
 ('km_folic_acid', 'cat_pregnancy', 'Folic Acid', 'Folic Acid', 'Various', '5mg', 'Tablet', 50, 0, 600, '', 'Essential vitamin for pregnancy and neural tube defect prevention.', 'Pregnancy supplement, folate deficiency, anemia', '1 tablet daily during pregnancy', 'Rare: nausea at high doses', 'Safe in pregnancy. Start before conception ideally.', 'Store below 25°C', 0, 1, 4.7),
 ('km_ferro_sulph', 'cat_pregnancy', 'Ferrous Sulphate', 'Ferrous Sulphate', 'Various', '200mg', 'Tablet', 60, 0, 800, '', 'Iron supplement for anemia in pregnancy.', 'Iron deficiency anemia, pregnancy anemia', '1 tablet 2-3 times daily', 'Constipation, dark stools, nausea', 'Take on empty stomach for best absorption. Take with vitamin C.', 'Store below 25°C', 0, 0, 4.4),
 ('km_pregnacare', 'cat_pregnancy', 'Pregnacare', 'Multivitamin', 'Vitabiotics', 'Standard', 'Tablet', 1200, 0, 150, '', 'Comprehensive pregnancy multivitamin with folic acid.', 'Pregnancy nutrition, pre-conception', '1 tablet daily with food', 'Rare: nausea', 'Available OTC. Safe in pregnancy.', 'Store below 25°C', 0, 0, 4.6),
 ('km_calcium', 'cat_pregnancy', 'Calcium Sandoz', 'Calcium', 'Novartis', '500mg', 'Tablet', 200, 0, 300, '', 'Calcium supplement for bone health in pregnancy.', 'Calcium supplementation in pregnancy, bone health', '1-2 tablets daily', 'Constipation, bloating', 'Take with food. Separate from iron by 2 hours.', 'Store below 25°C', 0, 0, 4.5),

-- ── Vitamins & Supplements ───────────────────────────────────────────────
 ('km_vitc', 'cat_vitamins', 'Vitamin C', 'Ascorbic Acid', 'Various', '1000mg', 'Tablet', 150, 0, 500, '', 'Vitamin C for immune support and antioxidant protection.', 'Immune support, scurvy prevention, antioxidant', '1 tablet daily', 'GI upset at high doses, kidney stones (excess)', 'Generally safe. Excess may cause diarrhea.', 'Store below 25°C', 0, 0, 4.5),
 ('km_vitd', 'cat_vitamins', 'Vitamin D3', 'Cholecalciferol', 'Various', '1000IU', 'Capsule', 200, 0, 350, '', 'Vitamin D for bone health and immunity.', 'Vitamin D deficiency, bone health, immunity', '1 capsule daily or as prescribed', 'Rare: hypercalcemia at very high doses', 'Take with fatty food for absorption.', 'Store below 25°C', 0, 0, 4.5),
 ('km_vitb', 'cat_vitamins', 'Neurobion', 'Vitamin B Complex', 'Merck', 'Standard', 'Tablet', 180, 0, 400, '', 'B vitamins for nerve health and energy.', 'B vitamin deficiency, nerve pain, fatigue', '1 tablet daily', 'Rare: nausea, itching', 'Generally safe. May cause bright yellow urine.', 'Store below 25°C', 0, 0, 4.4),
 ('km_zinc_tab', 'cat_vitamins', 'Zinc', 'Zinc Sulphate', 'Various', '20mg', 'Tablet', 80, 0, 500, '', 'Zinc supplement for immunity and growth.', 'Zinc deficiency, diarrhea management, wound healing', '1 tablet daily', 'Nausea, metallic taste', 'Take on empty stomach for best absorption.', 'Store below 25°C', 0, 0, 4.4),
 ('km_seven_seas', 'cat_vitamins', 'Seven Seas', 'Multivitamin', 'Seven Seas', 'Standard', 'Capsule', 600, 0, 300, '', 'Daily multivitamin for adults.', 'General nutrition, vitality', '1 capsule daily with food', 'Rare: GI upset', 'Available OTC.', 'Store below 25°C', 0, 0, 4.5),
 ('km_centrum', 'cat_vitamins', 'Centrum', 'Multivitamin', 'Pfizer', 'Standard', 'Tablet', 990, 0, 200, '', 'Complete daily multivitamin and mineral.', 'General nutrition support', '1 tablet daily with food', 'Rare: GI upset', 'Available OTC.', 'Store below 25°C', 0, 1, 4.6),
 ('km_iron_folic', 'cat_vitamins', 'Feroglobin', 'Iron/Folic Acid/B12', 'Haleon', 'Standard', 'Capsule', 350, 0, 300, '', 'Iron supplement with B vitamins for energy.', 'Iron deficiency anemia, fatigue', '1 capsule daily with food', 'Constipation, dark stools', 'Take on empty stomach for absorption.', 'Store below 25°C', 0, 0, 4.5),

-- ── Children's Medicine ──────────────────────────────────────────────────
 ('km_calpol', 'cat_children', 'Calpol', 'Paracetamol', 'Johnson & Johnson', '120mg/5ml', 'Suspension', 200, 0, 500, '', 'Paracetamol suspension for children fever and pain.', 'Fever, mild to moderate pain in children', 'As per age/weight on包装', 'Rare: nausea, allergic reactions', 'Do not exceed recommended dose. Measure carefully.', 'Store below 25°C', 0, 1, 4.8),
 ('km_piriton', 'cat_children', 'Piriton Syrup', 'Chlorpheniramine', 'GSK', '2mg/5ml', 'Syrup', 150, 0, 350, '', 'Antihistamine syrup for children allergies.', 'Allergic rhinitis, urticaria, itching in children', 'As per age on包装', 'Drowsiness, dry mouth', 'Causes drowsiness. Do not combine with other antihistamines.', 'Store below 25°C', 0, 0, 4.4),
 ('km_amoxil_syrup', 'cat_children', 'Amoxil Syrup', 'Amoxicillin', 'GSK Kenya', '125mg/5ml', 'Suspension', 250, 0, 300, '', 'Amoxicillin suspension for children infections.', 'Bacterial infections in children', 'As per weight every 8 hours', 'Diarrhea, nausea, rash', 'Complete full course. Shake well before use. Prescription required.', 'Store below 25°C', 1, 0, 4.5),
 ('km_zinc_syrup', 'cat_children', 'Zinc Syrup', 'Zinc Sulphate', 'Various', '10mg/5ml', 'Syrup', 100, 0, 400, '', 'Zinc supplement for diarrhea management in children.', 'Acute diarrhea in children, zinc deficiency', '10-20mg daily for 10-14 days', 'Nausea, vomiting at high doses', 'Use with ORS for diarrhea. WHO recommended.', 'Store below 25°C', 0, 0, 4.6),
 ('km_ors', 'cat_children', 'ORS', 'Oral Rehydration Salts', 'Various', 'Standard', 'Sachet', 30, 0, 800, '', 'WHO ORS for dehydration from diarrhea.', 'Dehydration from diarrhea, vomiting, heat', 'Dissolve 1 sachet in 1L clean water. Sip frequently.', 'Nausea if taken too fast', 'Available OTC. Essential for diarrhea management.', 'Store below 25°C', 0, 1, 4.8),
 ('km_vit_syrup', 'cat_children', 'Vitamin Syrup', 'Multivitamin', 'Various', 'Standard', 'Syrup', 200, 0, 300, '', 'Multivitamin syrup for children growth and development.', 'Nutritional supplementation in children', '5-10ml daily as per age', 'Rare: GI upset', 'Available OTC.', 'Store below 25°C', 0, 0, 4.4),
 ('km_nurofen_kids', 'cat_children', 'Nurofen for Children', 'Ibuprofen', 'Reckitt', '100mg/5ml', 'Suspension', 250, 0, 350, '', 'Ibuprofen for children fever and pain.', 'Fever, pain in children over 3 months', 'As per age/weight on包装', 'Stomach upset, nausea', 'Not for children under 3 months. Take with food.', 'Store below 25°C', 0, 1, 4.7),

-- ── HIV / ARVs ───────────────────────────────────────────────────────────
 ('km_tld', 'cat_hiv', 'TLD', 'Tenofovir/Lamivudine/Dolutegravir', 'Various', '300/300/50mg', 'Tablet', 50, 0, 500, '', 'First-line ARV combination therapy.', 'HIV treatment (first-line)', '1 tablet once daily with food', 'Nausea, headache, insomnia, weight gain', 'Prescription required. Do not miss doses. lifelong therapy.', 'Store below 25°C', 1, 1, 4.6),
 ('km_tle', 'cat_hiv', 'TLE', 'Tenofovir/Lamivudine/Efavirenz', 'Various', '300/300/600mg', 'Tablet', 40, 0, 300, '', 'ARV combination (older regimen).', 'HIV treatment', '1 tablet once daily at bedtime', 'Dizziness, vivid dreams, rash, insomnia', 'Prescription required. Take at bedtime initially.', 'Store below 25°C', 1, 0, 4.3),
 ('km_dolutegravir', 'cat_hiv', 'Tivicay', 'Dolutegravir', 'ViiV', '50mg', 'Tablet', 2500, 0, 100, '', 'Integrase inhibitor for HIV treatment.', 'HIV treatment (second-line)', '50mg once or twice daily as prescribed', 'Insomnia, headache, nausea', 'Prescription required. High barrier to resistance.', 'Store below 25°C', 1, 0, 4.5),
 ('km_lamivudine', 'cat_hiv', 'Epivir', 'Lamivudine', 'Various', '150mg', 'Tablet', 200, 0, 200, '', 'NRTI for HIV and hepatitis B.', 'HIV treatment, hepatitis B', '150mg twice daily', 'Nausea, headache, fatigue', 'Prescription required. Also active against hepatitis B.', 'Store below 25°C', 1, 0, 4.2),
 ('km_tenofovir', 'cat_hiv', 'Viread', 'Tenofovir', 'Gilead', '300mg', 'Tablet', 1500, 0, 100, '', 'NRTI for HIV treatment.', 'HIV treatment', '300mg once daily', 'Nausea, kidney effects, bone density loss', 'Prescription required. Monitor kidney function.', 'Store below 25°C', 1, 0, 4.3),
 ('km_zidovudine', 'cat_hiv', 'Retrovir', 'Zidovudine', 'Various', '300mg', 'Tablet', 300, 0, 150, '', 'NRTI for HIV treatment.', 'HIV treatment (second-line)', '300mg twice daily', 'Anemia, nausea, headache, fatigue', 'Prescription required. Monitor blood count.', 'Store below 25°C', 1, 0, 4.1),
 ('km_abacavir', 'cat_hiv', 'Ziagen', 'Abacavir', 'ViiV', '600mg', 'Tablet', 2000, 0, 80, '', 'NRTI for HIV treatment.', 'HIV treatment', '600mg once daily or 300mg twice daily', 'Nausea, vomiting, hypersensitivity reaction', 'Prescription required. HLA-B*5701 testing recommended.', 'Store below 25°C', 1, 0, 4.3),

-- ── TB Medicines ─────────────────────────────────────────────────────────
 ('km_rifampicin', 'cat_tb', 'Rifampicin', 'Rifampicin', 'Various', '300mg', 'Capsule', 150, 0, 300, '', 'First-line TB medicine.', 'Tuberculosis treatment', '600mg once daily (450mg if <50kg)', 'Orange discoloration of body fluids, nausea, hepatotoxicity', 'Prescription required. Turns urine/sweat orange. Lifelong adherence.', 'Store below 25°C', 1, 0, 4.3),
 ('km_isoniazid', 'cat_tb', 'Isoniazid', 'Isoniazid', 'Various', '300mg', 'Tablet', 80, 0, 400, '', 'First-line TB medicine.', 'Tuberculosis treatment, TB prevention', '300mg once daily', 'Peripheral neuropathy, hepatotoxicity', 'Prescription required. Take with vitamin B6.', 'Store below 25°C', 1, 0, 4.2),
 ('km_pyrazinamide', 'cat_tb', 'Pyrazinamide', 'Pyrazinamide', 'Various', '500mg', 'Tablet', 120, 0, 300, '', 'First-line TB medicine.', 'Tuberculosis treatment (intensive phase)', '1500mg once daily (weight-based)', 'Joint pain, nausea, hepatotoxicity', 'Prescription required. Monitor liver function.', 'Store below 25°C', 1, 0, 4.1),
 ('km_ethambutol', 'cat_tb', 'Ethambutol', 'Ethambutol', 'Various', '400mg', 'Tablet', 100, 0, 300, '', 'First-line TB medicine.', 'Tuberculosis treatment', '15-25mg/kg once daily', 'Visual disturbances, peripheral neuropathy', 'Prescription required. Regular eye examinations needed.', 'Store below 25°C', 1, 0, 4.0),
 ('km_rhze', 'cat_tb', 'RHZE Combination', 'Rifampicin/Isoniazid/Pyrazinamide/Ethambutol', 'Various', 'Fixed-dose', 'Tablet', 200, 0, 500, '', 'Fixed-dose combination for TB intensive phase.', 'TB treatment (intensive phase)', 'As per weight band once daily', 'Nausea, hepatotoxicity, orange discoloration', 'Prescription required. Complete full 6-month course.', 'Store below 25°C', 1, 0, 4.3),

-- ── Deworming ────────────────────────────────────────────────────────────
 ('km_albendazole', 'cat_deworming', 'Zentel', 'Albendazole', 'GSK', '400mg', 'Tablet', 100, 0, 600, '', 'Broad-spectrum deworming medicine.', 'Roundworm, hookworm, whipworm, tapeworm, pinworm', '400mg single dose (repeat in 2 weeks)', 'Nausea, abdominal pain, diarrhea', 'Available OTC. Repeat dose in 2 weeks. Safe from age 2.', 'Store below 25°C', 0, 1, 4.6),
 ('km_mebendazole', 'cat_deworming', 'Vermox', 'Mebendazole', 'Janssen', '100mg', 'Tablet', 150, 0, 400, '', 'Deworming medicine for intestinal worms.', 'Roundworm, pinworm, hookworm', '100mg twice daily for 3 days or 500mg single dose', 'Nausea, abdominal pain', 'Available OTC. Repeat in 2 weeks.', 'Store below 25°C', 0, 0, 4.5),
 ('km_praziquantel', 'cat_deworming', 'Biltricide', 'Praziquantel', 'Bayer', '600mg', 'Tablet', 500, 0, 150, '', 'Antiparasitic for schistosomiasis and tapeworm.', 'Schistosomiasis, tapeworm, liver fluke', '40-60mg/kg single dose as prescribed', 'Nausea, dizziness, abdominal pain', 'Prescription required. Take with food.', 'Store below 25°C', 1, 0, 4.3),

-- ── Anti-Seizure ─────────────────────────────────────────────────────────
 ('km_carbamazepine', 'cat_anti_seizure', 'Tegretol', 'Carbamazepine', 'Novartis', '200mg', 'Tablet', 200, 0, 200, '', 'Anticonvulsant for seizures and nerve pain.', 'Epilepsy, trigeminal neuralgia', '200mg twice daily, increase as prescribed', 'Dizziness, drowsiness, nausea, rash, blood disorders', 'Prescription required. Monitor blood count. Many drug interactions.', 'Store below 25°C', 1, 0, 4.3),
 ('km_sodium_valproate', 'cat_anti_seizure', 'Epilim', 'Sodium Valproate', 'Sanofi', '500mg', 'Tablet', 200, 0, 200, '', 'Broad-spectrum anticonvulsant.', 'Epilepsy, bipolar disorder, migraine prevention', '500mg twice daily as prescribed', 'Weight gain, hair loss, tremor, liver toxicity', 'Prescription required. Teratogenic - avoid in pregnancy.', 'Store below 25°C', 1, 0, 4.2),
 ('km_phenytoin', 'cat_anti_seizure', 'Epanutin', 'Phenytoin', 'Various', '100mg', 'Capsule', 100, 0, 200, '', 'Anticonvulsant for seizures.', 'Epilepsy (tonic-clonic seizures)', '100mg 2-3 times daily as prescribed', 'Gingival hyperplasia, drowsiness, rash, coordination problems', 'Prescription required. Narrow therapeutic index.', 'Store below 25°C', 1, 0, 4.1),
 ('km_phenobarbital', 'cat_anti_seizure', 'Gardenal', 'Phenobarbital', 'Various', '60mg', 'Tablet', 80, 0, 200, '', 'Barbiturate anticonvulsant.', 'Epilepsy, neonatal seizures', 'As prescribed (narrow therapeutic index)', 'Drowsiness, cognitive effects, respiratory depression', 'Prescription required. Highly sedating. Narrow therapeutic index.', 'Store below 25°C', 1, 0, 4.0),
 ('km_levetiracetam', 'cat_anti_seizure', 'Keppra', 'Levetiracetam', 'UCB', '500mg', 'Tablet', 800, 0, 150, '', 'Newer anticonvulsant with fewer interactions.', 'Epilepsy', '500mg twice daily as prescribed', 'Drowsiness, behavioral changes, dizziness', 'Prescription required. Fewer drug interactions than older AEDs.', 'Store below 25°C', 1, 0, 4.4),

-- ── Mental Health ────────────────────────────────────────────────────────
 ('km_amitriptyline', 'cat_mental_health', 'Tryptizol', 'Amitriptyline', 'Various', '25mg', 'Tablet', 100, 0, 200, '', 'Tricyclic antidepressant for depression and nerve pain.', 'Depression, neuropathic pain, migraine prophylaxis', '25mg at bedtime, increase as prescribed', 'Drowsiness, dry mouth, constipation, weight gain', 'Prescription required. Take at bedtime. Do not stop suddenly.', 'Store below 25°C', 1, 0, 4.2),
 ('km_diazepam', 'cat_mental_health', 'Valium', 'Diazepam', 'Roche', '5mg', 'Tablet', 150, 0, 200, '', 'Benzodiazepine for anxiety and seizures.', 'Severe anxiety, seizures, muscle spasms', '5mg 2-3 times daily as prescribed', 'Drowsiness, dependence, respiratory depression', 'Controlled substance. Risk of dependence. Short-term use only.', 'Store below 25°C', 1, 0, 4.1),
 ('km_alprazolam', 'cat_mental_health', 'Xanax', 'Alprazolam', 'Pfizer', '0.5mg', 'Tablet', 200, 0, 150, '', 'Benzodiazepine for severe anxiety and panic.', 'Severe anxiety, panic disorder', '0.25-0.5mg 3 times daily as prescribed', 'Drowsiness, dependence, coordination problems', 'Controlled substance. Risk of dependence. Prescription required.', 'Store below 25°C', 1, 0, 4.0),
 ('km_fluoxetine', 'cat_mental_health', 'Prozac', 'Fluoxetine', 'Lilly', '20mg', 'Capsule', 400, 0, 200, '', 'SSRI antidepressant for depression and anxiety.', 'Depression, anxiety, OCD, bulimia', '20mg once daily, increase as prescribed', 'Nausea, insomnia, anxiety (initial), sexual dysfunction', 'Prescription required. Takes 2-4 weeks to work. Do not stop suddenly.', 'Store below 25°C', 1, 0, 4.4),
 ('km_sertraline', 'cat_mental_health', 'Lustral', 'Sertraline', 'Pfizer', '50mg', 'Tablet', 350, 0, 200, '', 'SSRI for depression, anxiety, PTSD.', 'Depression, anxiety, PTSD, OCD', '50mg once daily', 'Nausea, insomnia, diarrhea, sexual dysfunction', 'Prescription required. Takes 2-4 weeks to work.', 'Store below 25°C', 1, 0, 4.3),
 ('km_haloperidol', 'cat_mental_health', 'Haldol', 'Haloperidol', 'Various', '5mg', 'Tablet', 120, 0, 150, '', 'Typical antipsychotic for acute psychosis.', 'Acute psychosis, schizophrenia', 'As prescribed by psychiatrist', 'Extrapyramidal effects, sedation, tardive dyskinesia', 'Prescription required. Monitor for movement disorders.', 'Store below 25°C', 1, 0, 4.0),
 ('km_risperidone', 'cat_mental_health', 'Risperdal', 'Risperidone', 'Janssen', '2mg', 'Tablet', 300, 0, 200, '', 'Atypical antipsychotic for psychosis and mood disorders.', 'Schizophrenia, bipolar disorder', '1-2mg twice daily as prescribed', 'Weight gain, sedation, metabolic effects, tremor', 'Prescription required. Monitor metabolic parameters.', 'Store below 25°C', 1, 0, 4.2),
 ('km_olanzapine', 'cat_mental_health', 'Zyprexa', 'Olanzapine', 'Lilly', '10mg', 'Tablet', 500, 0, 100, '', 'Atypical antipsychotic for schizophrenia and bipolar.', 'Schizophrenia, bipolar disorder', '10-15mg once daily as prescribed', 'Weight gain, sedation, metabolic effects, diabetes risk', 'Prescription required. Monitor weight and metabolic parameters.', 'Store below 25°C', 1, 0, 4.1),

-- ── Controlled Medicines ─────────────────────────────────────────────────
 ('km_morphine', 'cat_controlled', 'Morphine', 'Morphine Sulphate', 'Various', '10mg', 'Tablet', 300, 0, 50, '', 'Opioid analgesic for severe pain.', 'Severe pain (cancer, post-surgical)', 'As prescribed by physician', 'Respiratory depression, constipation, nausea, dependence', 'Controlled substance (Sched. II). Prescription required. Strict monitoring.', 'Store below 25°C', 1, 0, 4.3),
 ('km_pethidine', 'cat_controlled', 'Pethidine', 'Pethidine', 'Various', '50mg', 'Injection', 200, 0, 30, '', 'Opioid for acute severe pain.', 'Acute severe pain (short-term)', '50-150mg IM/IV as prescribed', 'Respiratory depression, seizures, dependence', 'Controlled substance. Short-term use only. Prescription required.', 'Store below 25°C', 1, 0, 4.1),
 ('km_codeine', 'cat_controlled', 'Codeine', 'Codeine Phosphate', 'Various', '30mg', 'Tablet', 100, 0, 200, '', 'Weak opioid for moderate pain and cough.', 'Moderate pain, severe cough', '15-60mg every 4-6 hours as prescribed', 'Constipation, drowsiness, nausea, dependence', 'Controlled substance. Risk of dependence with prolonged use.', 'Store below 25°C', 1, 0, 4.1),
 ('km_fentanyl_tab', 'cat_controlled', 'Subutex', 'Buprenorphine', 'Various', '2mg', 'Sublingual Tablet', 400, 0, 30, '', 'Partial opioid agonist for opioid dependence.', 'Opioid dependence treatment', 'As prescribed by specialist', 'Precipitated withdrawal, headache, nausea', 'Controlled substance. Prescribed by addiction specialist only.', 'Store below 25°C', 1, 0, 4.2),
 ('km_ketamine_inj', 'cat_controlled', 'Ketamine', 'Ketamine', 'Various', '50mg/ml', 'Injection', 500, 0, 20, '', 'Dissociative anaesthetic for procedures and refractory pain.', 'Anaesthesia for procedures, refractory pain, sedation', 'As administered by anaesthetist', 'Hallucinations, nausea, emergence reactions', 'Controlled substance. Hospital use only. Administration by anaesthetist.', 'Store below 25°C', 1, 0, 4.3);
